### PR TITLE
Deleted my files and added the BC project template.

### PR DESCRIPTION
**Pull request by DavidEdwards**

### CODE REVIEW

**Review by Movian — APPROVED** [review]
looks like you uploaded the initial project, Will pull after approval and check the gradle stuff still works.

**Comment by DavidEdwards** [comment]
Indeed, I used their project. They are using gradle (my project wasn't) and they have a project that works directly. Makes a lot more sense to use their pre-built system.

**Comment by Movian** [comment]
yeah, I just created a local version and tested Gradle, it builds the test client correctly. So a good start!

Will try and compile the test players and try a test match in the client. If that works well we should be in a good place to get started.

**Comment by Movian** [comment]
ok did a commi and push after testing and generating a copy of the example player to use as our base player. 

It says it committed and pushed but wanted to check I am using the right workflow for the peer review....  but i don't see it on github

**Comment by DavidEdwards** [comment]
Check that you are looking at the dev branch on github. I see your commit.

**Comment by Movian** [comment]
Hey Dave,

we had some initial issues getting some things working and after speaking with the Battelcode guys their suggestion is we setup our own local copies of the frame work and we only put the Src folder under SCM. 

Whats going to be the easiest way to clear out the file and just manage the src folder?

**Comment by DavidEdwards** [comment]
What issue did you have? There's no reason it shouldn't work as it is.

**Comment by Movian** [comment]
When we run the gradle build and it generates the client but client can't read the maps or the players....

which makes testing tricky.

**Comment by DavidEdwards** [comment]
It works for me. Hmm.

You ran `gradlew run`?

**Comment by Movian** [comment]
It worked for me, it was Sam that had the problem….

**Comment by DavidEdwards** [comment]
I will try running the current project again. You made a lot of changes in the dev branch. Some in configuration files. I could be that broke something.

@McGreeb could try checking out the `master` branch to see if that works?

If it works for us both, the fix isn't to do some weird git repository. The fix is to find out what happened on Sams end.

**Comment by ghost** [comment]
Can we get https://github.com/battleooze1885 added to the project please :)

**Comment by DavidEdwards** [comment]
Added him!

**Comment by ghost** [comment]
You sure? cant see repo in his IDE

**Comment by DavidEdwards** [comment]
Certain, he will need to check it out.

**Comment by ghost** [comment]
We got it, he hadn't accepted the invite :)

**Comment by DavidEdwards** [comment]
Did you manage to compile / run the project?

**Comment by ghost** [comment]
Yeah not sure what went wrong first time, fine now, dev's still recommend only have src folder in version control though

**Pull request merged**
